[[language]]
name = "python"
auto-format = true
language-servers = [
  {name = "pyright"},
  {name = "ruff-lsp"},
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typst"
file-types = ["typst", "typ"]
roots = []
comment-token = "//"
language-servers = ["typst-lsp"]
indent = { tab-width = 2, unit = " " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'

[[grammar]]
name = "typst"
source.path = "/Users/qoqosz/.config/helix/runtime/grammars/sources/typst"
# source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "e35aa22395fdde82bbc4b5700c324ce346dfc9e5" }

[language-server.typst-lsp]
command = "typst-lsp"
args = []
config = {}
